- name: install haproxy
  apt: >
    name={{item}}
    state=present
  with_items: [ haproxy ]
  become: yes
  notify: "restart haproxy"

- name: configure haproxy
  template: >
    src=haproxy.cfg.j2
    dest=/etc/haproxy/haproxy.cfg
  become: yes
  become_method: sudo
  notify: "restart haproxy"
