- name: 'restart haproxy - systemctl'
  become: yes
  systemd: >
    service=haproxy
    state=restarted
  when: >
    ansible_distribution_major_version|int >= 16

- name: 'restart haproxy - upstart'
  become: yes
  service: >
    name=haproxy
    state=restarted
  when: >
    ansible_distribution_major_version|int < 16


