- name: Install required packages git, vim, libgit2-dev
  apt: >
    name={{item}}
    state=present
  with_items: [ git, vim, libgit2-dev ]
  become: yes

- name: Create electricbook user
  user: >
    name=electricbook
    shell=/bin/bash
  become: yes

- name: Install electric-book-gui from GIT
  git: >
    repo={{git_repo}}
    dest=/opt/electricbook
  become: yes

- name: Set permissions on git_cache
  file: >
    name=/opt/electricbook/git_cache
    owner=electricbook
    group=electricbook
    recurse=yes
  become: yes

- name: Create /opt/electricbook/bin
  file: >
    name=/opt/electricbook/bin
    state=directory
    mode=0755
  become: yes

- name: install electricbook server from local version
  copy: >
    dest=/opt/electricbook/bin/electricbook
    force=yes
    src=electricbook
    mode=0755
  become: yes 
  notify: 'restart electricbook'

- name: install electricbook configuration electricbook-0.yml
  template: >
    dest=/opt/electricbook/electricbook-0.yml
    src=electricbook-0.yml.j2
    mode=0755
  become: yes
  notify: 'restart electricbook'

- name: configure upstart for electricbook
  when: >
    ansible_distribution_major_version|int < 16
  template: >
    src=upstart.electricbook.conf.j2
    dest=/etc/init/electricbook.conf
  become: yes
  become_method: sudo
  notify: "restart electricbook"

- name: configure systemd for electricbook
  when: >
    ansible_distribution_major_version|int >= 16
  include: systemd.yml
  notify: "restart electricbook"

- include: nginx.yml
  when: >
    'nginx'==webserver

