# Our dependency on rvm_io.ruby will install rvm and bundler
- name: install bookworks prereqs
  apt: >
    name={{item}}
    state=present
    force=yes
  with_items:
    - git
    - curl
    - vim
    - libcurl4
    - libfontconfig1
    - libfreetype6
    - libgif7
    - libjpeg8
    - libtiff5
    - libxml2
    - libcairo2
    - libpixman-1-0
  become: yes

- name: installrvm
  tags: ruby
  include_role:
    name: rvm_io.ruby
  vars:
    rvm1_rubies: ['ruby-2.4.0']
    rvm1_user: "root"
    rvm1_install_path: /usr/local/rvm

# - name: copy libpng12
#   become: yes
#   copy: >
#     src=libpng12-ubuntu_amd64.deb
#     dest=/tmp/libpng12.deb

- name: install libpng12
  become: yes
  apt: >
    deb=http://za.archive.ubuntu.com/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1_amd64.deb
    state=present

- name: install prince
  become: yes
  script: install-prince.sh

- name: bookworks-test-install
  become: yes
  script: install-first-run.sh

- name: "install prereqs for phantomjs"
  apt: >
    name={{item}}
    state=present
  with_items:
    - build-essential
    - chrpath
    - libssl-dev
    - libxft-dev
    - libfreetype6-dev
    - libfreetype6
    - libfontconfig1-dev
    - libfontconfig1
  become: yes

- name: fetch phantomjs
  get_url: >
    url="https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2"
    dest="/usr/local/share/phantomjs.tar.gz"
  become: yes

- name: untar phantomjs
  unarchive: >
    remote_src=yes
    src="/usr/local/share/phantomjs.tar.gz"
    dest="/usr/local/share"
  become: yes

- name: link phantomjs
  become: yes
  file: >
    state=link
    src=/usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs
    dest=/usr/local/bin/phantomjs
  
