# Our dependency on rvm_io.ruby will install rvm and bundler
- name: install bookworks prereqs
  apt: >
    name={{item}}
    state=present
    force=yes
  with_items:
    - git
    - curl
    - vim
    - libcurl3
    - libfontconfig1
    - libfreetype6
    - libgif7
    - libjpeg8
    - libtiff5
    - libxml2
    - libcairo2
    - libpixman-1-0
  become: yes

# - name: copy libpng12
#   become: yes
#   copy: >
#     src=libpng12-ubuntu_amd64.deb
#     dest=/tmp/libpng12.deb

- name: install libpng12
  become: yes
  apt: >
    deb=http://za.archive.ubuntu.com/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1_amd64.deb
    state=present

- name: install prince
  become: yes
  script: install-prince.sh

- name: bookworks-test-install
  become: yes
  script: install-first-run.sh