# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Electric Book Manager user docs
email: support@electricbook.works
description: >- # this means to ignore newlines until "baseurl:"
  Documentation for the Electric Book Manager, a web application for
  using the Electric Book workflow from anywhere.
baseurl: "/electric-book-gui" # the subpath of your site, e.g. /blog
url: "http://electricbook.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Set pretty permalinks, not Jekyll default 'date'
permalink: pretty

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - package.json
  - package-lock.json
  - gulpfile.js
  - CNAME

# kramdown options (see http://kramdown.gettalong.org/options.html)
# auto_id_stripping remove formatting from headings before generating IDs
# which keeps your IDs neat and tidy, and links persistent even if you format headings
kramdown:
  auto_id_stripping: true

# Set default page layout for all pages
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      excerpt: ""

collections:
  users:
    output: true
  developers:
    output: true
